/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SimplexPanel.java
 *
 * Created on 2-dic-2011, 13.03.32
 */
package javaapplication1;

/**
 *
 * @author mwimola
 */
public class SimplexPanel extends javax.swing.JPanel {
    boolean _generateButclick = false;
    /** Creates new form SimplexPanel */
    public SimplexPanel() {
        initComponents();
        _panelSystem.setVisible(false);
        _tableauPanel.setVisible(false);
        _generaTabBut.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _inputEqVar = new javax.swing.JPanel();
        _labelEq = new javax.swing.JLabel();
        _labelVar = new javax.swing.JLabel();
        _newProblem = new javax.swing.JButton();
        _generateProblem = new javax.swing.JButton();
        _comboEq = new javax.swing.JComboBox();
        _comboVar = new javax.swing.JComboBox();
        _panelSystem = new javaapplication1.PanelSystem();
        _tableauPanel = new javaapplication1.TableauPanel();
        _generaTabBut = new javax.swing.JButton();
        _errorMsg = new javax.swing.JLabel();

        _labelEq.setText("Number of Constraints:");

        _labelVar.setText("Number of Variables:");

        _newProblem.setText("New Problem");
        _newProblem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _newProblemActionPerformed(evt);
            }
        });

        _generateProblem.setText("Generate Problem");
        _generateProblem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _generateProblemActionPerformed(evt);
            }
        });

        _comboEq.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        _comboEq.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                _comboEqItemStateChanged(evt);
            }
        });

        _comboVar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "6" }));
        _comboVar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                _comboVarItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout _inputEqVarLayout = new javax.swing.GroupLayout(_inputEqVar);
        _inputEqVar.setLayout(_inputEqVarLayout);
        _inputEqVarLayout.setHorizontalGroup(
            _inputEqVarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_inputEqVarLayout.createSequentialGroup()
                .addComponent(_newProblem)
                .addGap(141, 141, 141)
                .addGroup(_inputEqVarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_labelVar)
                    .addComponent(_generateProblem)
                    .addComponent(_labelEq))
                .addGap(16, 16, 16)
                .addGroup(_inputEqVarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_comboVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_comboEq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        _inputEqVarLayout.setVerticalGroup(
            _inputEqVarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_inputEqVarLayout.createSequentialGroup()
                .addGroup(_inputEqVarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(_inputEqVarLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(_inputEqVarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_labelEq)
                            .addComponent(_comboEq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(_inputEqVarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_labelVar)
                            .addComponent(_comboVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(_newProblem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(_generateProblem))
        );

        _generaTabBut.setText("Generate Tableau");
        _generaTabBut.setEnabled(false);
        _generaTabBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _generaTabButActionPerformed(evt);
            }
        });

        _errorMsg.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12));
        _errorMsg.setForeground(new java.awt.Color(204, 0, 0));
        _errorMsg.setText("          ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_inputEqVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_panelSystem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_tableauPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(_generaTabBut))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(_errorMsg)))
                .addContainerGap(671, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_inputEqVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_panelSystem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(_tableauPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_generaTabBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_errorMsg)
                .addContainerGap(367, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void _generaTabButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__generaTabButActionPerformed
        
        _errorMsg.setText("");   
        Frazione[][] generata = new Frazione[1][1];
        try
        {
            generata = _panelSystem.GenerateMatrix(Integer.parseInt(_comboEq.getSelectedItem().toString()),Integer.parseInt(_comboVar.getSelectedItem().toString()));
        }
        catch(Exception e)
        {
            _errorMsg.setText("Invalid input: data must be type of Integer");
            _panelSystem.repaint();
            return;
        }   
        
        _generaTabBut.setEnabled(false);

        {
            
             _tableauPanel.setTableau(new Tableau(generata),_panelSystem.isMin())  ;
             _tableauPanel.setVisible(true);
             _panelSystem.setVisible(false);
             _generaTabBut.setVisible(false);
        }
    }//GEN-LAST:event__generaTabButActionPerformed

    private void _newProblemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__newProblemActionPerformed
        _panelSystem.resetSystem();
        _panelSystem.setVisible(false);
        _tableauPanel.setVisible(false);
        _generaTabBut.setVisible(false);
        _generateButclick = false;
    }//GEN-LAST:event__newProblemActionPerformed

    private void _generateProblemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__generateProblemActionPerformed
        _panelSystem.setVisible(true);
        _generaTabBut.setVisible(true);
        _generaTabBut.setEnabled(true);
        _tableauPanel.setVisible(false);
        _panelSystem.SetSystem(Integer.parseInt(_comboEq.getSelectedItem().toString()),Integer.parseInt(_comboVar.getSelectedItem().toString()));   
        _generateButclick = true;
    }//GEN-LAST:event__generateProblemActionPerformed

    private void _comboEqItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event__comboEqItemStateChanged
        if(_generateButclick)
        {
        _panelSystem.setVisible(true);
        _generaTabBut.setVisible(true);
        _generaTabBut.setEnabled(true);
        _tableauPanel.setVisible(false);
        _panelSystem.SetSystem(Integer.parseInt(_comboEq.getSelectedItem().toString()),Integer.parseInt(_comboVar.getSelectedItem().toString()));  
        }
    }//GEN-LAST:event__comboEqItemStateChanged

    private void _comboVarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event__comboVarItemStateChanged
        if(_generateButclick)
        {
        _panelSystem.setVisible(true);
        _generaTabBut.setVisible(true);
        _generaTabBut.setEnabled(true);
        _tableauPanel.setVisible(false);
        _panelSystem.SetSystem(Integer.parseInt(_comboEq.getSelectedItem().toString()),Integer.parseInt(_comboVar.getSelectedItem().toString()));  
        }        // TODO add your handling code here:
    }//GEN-LAST:event__comboVarItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox _comboEq;
    private javax.swing.JComboBox _comboVar;
    private javax.swing.JLabel _errorMsg;
    private javax.swing.JButton _generaTabBut;
    private javax.swing.JButton _generateProblem;
    private javax.swing.JPanel _inputEqVar;
    private javax.swing.JLabel _labelEq;
    private javax.swing.JLabel _labelVar;
    private javax.swing.JButton _newProblem;
    private javaapplication1.PanelSystem _panelSystem;
    private javaapplication1.TableauPanel _tableauPanel;
    // End of variables declaration//GEN-END:variables
}
