/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelSystem.java
 *
 * Created on 20-nov-2011, 14.49.22
 */
package javaapplication1;

/**
 *
 * @author mwimola
 */
public class PanelSystem extends javax.swing.JPanel {
    private static int MAX_EQ = 5;
    private static int MAX_VAR = 6;
    
    private PanelEq[] _eqs = new PanelEq[MAX_EQ];
   
    
    public  Frazione[][] GenerateMatrix(int numEq, int numVar)
    {
        int colonneInPiu = 0;
        int zeri= 0;
        Frazione[] temp = null;
        
        for(int i= 0 ; i<numEq; i++)
        {
            if(_eqs[i].AddSurplusOrSlack())
                colonneInPiu ++;
        }
        
        Frazione[][] matrix = new Frazione[1 + numEq][1 + numVar + colonneInPiu];    //1+ numEq -> funzione obiettivo + equazioni
                                                                                  //1 + variabili + le colonne di var surplus/slack
        matrix[0][0] = new Frazione(0);
        
        Frazione[] rigaProblema = _problem.GetValues(numVar);
        if(_minmax.getSelectedItem().toString().equals("max")){
            for(int i = 0; i<rigaProblema.length; i++)
            {
                rigaProblema[i] = rigaProblema[i].Moltiplicazione(new Frazione(-1));
            }
        }
        System.arraycopy(rigaProblema, 0 , matrix[0], 1, rigaProblema.length); 
        
        for(int j= rigaProblema.length + 1; j< matrix[0].length ; j++)
        {
            matrix[0][j] = new Frazione(0);
        }  
        
        for(int i=1; i<numEq+1; i++)
        {
            // temp = new Frazione[1 + numVar + zeri];
            temp = _eqs[i-1].GetRow(numVar, zeri);

            for(int j =0; j< temp.length; j++)
            {
                matrix[i][j] = temp[j];
            }
            
            for(int j= temp.length; j< matrix[i].length ; j++)
            {
                matrix[i][j] = new Frazione(0);
            }
            
            if(_eqs[i-1].AddSurplusOrSlack())
                zeri++;
            
        }
        
        
        //Tableau t = new Tableau(tab); 
        return matrix;
    }
    
    /** Creates new form PanelSystem */
    public PanelSystem() {
        initComponents();
        
        _eqs[0] = panelEq1;
        _eqs[1] = panelEq2;
        _eqs[2] = panelEq3;
        _eqs[3] = panelEq4;
        _eqs[4] = panelEq5;
        
        for(int i=0; i<_eqs.length; i++)
        {
            _eqs[i].setVisible(false);
        }
        
        _minmax.setVisible(false);
        _problem.setVisible(false);   
    }

    public void SetSystem(int numEq, int numVar)
    {
        _minmax.setVisible(false);
        _problem.setVisible(false);
     
        for(int i=0; i<_eqs.length; i++)
        {
            _eqs[i].setVisible(false);
        }
        
        _minmax.setVisible(true);
        _problem.setVisible(true);
        _problem.SetNumVars(numVar);
        for(int i=0; i<numEq; i++)
        {
            _eqs[i].setVisible(true);
            _eqs[i].getPanelVars().SetNumVars(numVar);
        }
    }
    public boolean isMin()
    {
        if(_minmax.getSelectedItem().toString().equals("min"))
            return true;
        else return false;
    }
    public void resetSystem()
    {
        _problem.resetValues();
        for(PanelEq p : _eqs)
        {
            p.resetEq();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEq1 = new javaapplication1.PanelEq();
        panelEq2 = new javaapplication1.PanelEq();
        panelEq3 = new javaapplication1.PanelEq();
        panelEq4 = new javaapplication1.PanelEq();
        panelEq5 = new javaapplication1.PanelEq();
        _problem = new javaapplication1.PanelVars();
        _minmax = new javax.swing.JComboBox();

        _minmax.setFont(new java.awt.Font("Arial", 0, 14));
        _minmax.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "min", "max" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_minmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEq5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelEq4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelEq3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelEq2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelEq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_problem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(_problem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(panelEq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelEq2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelEq3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelEq4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelEq5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(_minmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox _minmax;
    private javaapplication1.PanelVars _problem;
    private javaapplication1.PanelEq panelEq1;
    private javaapplication1.PanelEq panelEq2;
    private javaapplication1.PanelEq panelEq3;
    private javaapplication1.PanelEq panelEq4;
    private javaapplication1.PanelEq panelEq5;
    // End of variables declaration//GEN-END:variables
}
