/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelEq.java
 *
 * Created on 20-nov-2011, 14.15.58
 */
package javaapplication1;

/**
 *
 * @author mwimola
 */
public class PanelEq extends javax.swing.JPanel {
    
    
    /** Creates new form PanelEq */
    public PanelEq() {
        initComponents();
        _panelb.SetX("");
    }

    public PanelVars getPanelVars()
    {
        return _panelVars;
    }
    
    public Frazione[] GetRow(int numVars,int numZeri)
    {
        Frazione[] result;
        Frazione[] temp1 = _panelVars.GetValues(numVars);
        Frazione[] temp2 = new Frazione[temp1.length + 1 + numZeri];
        
        Frazione b = _panelb.getValue();
                
        temp2[0] = b;
        System.arraycopy(temp1, 0, temp2, 1, numVars);
        for(int i=temp1.length + 1; i< temp2.length; i++)
        {
            temp2[i] = new Frazione(0);
        }
        
        String segno = _segno.getSelectedItem().toString();
        if(segno.equals("="))
            result = new Frazione[temp2.length];
        else
            result = new Frazione[temp2.length + 1];
        
        System.arraycopy(temp2, 0, result, 0, temp2.length);
        
        if(segno.equals("≤"))
            result[temp2.length] = new Frazione(1);
        if(segno.equals("≥"))
            result[temp2.length] = new Frazione(-1);
        
        if(b.compareTo(new Frazione(0)) == -1)                      //SE bi <0 si cambia segno all'equazione corrispondente
        {
            for(int j=0; j< result.length; j++)
                result[j] = result[j].Moltiplicazione(new Frazione(-1));
        }
                
        return result;
    }
    
    public boolean AddSurplusOrSlack()
    {
        if(_segno.getSelectedItem().equals("="))
            return false;
        else return true;
    }
    
    public void resetEq()
    {
        _panelVars.resetValues();
        _panelb.setValue("");
        _segno.setSelectedIndex(0);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _panelVars = new javaapplication1.PanelVars();
        _segno = new javax.swing.JComboBox();
        _panelb = new javaapplication1.PanelVar();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        _segno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "≤", "≥", "=" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(_panelVars, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_segno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_panelb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_panelVars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_segno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_panelb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javaapplication1.PanelVars _panelVars;
    private javaapplication1.PanelVar _panelb;
    private javax.swing.JComboBox _segno;
    // End of variables declaration//GEN-END:variables
}
