/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TableauApp.java
 *
 * Created on 24-nov-2011, 13.07.41
 */
package javaapplication1;

/**
 *
 * @author mwimola
 */
public class TableauApp extends javax.swing.JFrame {

    /** Creates new form TableauApp */
    public TableauApp() {
        initComponents();
        _panelSystem.setVisible(false);
        _generaTabBut.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _inputEqVar = new javax.swing.JPanel();
        _labelEq = new javax.swing.JLabel();
        _labelVar = new javax.swing.JLabel();
        _comboEq = new javax.swing.JComboBox();
        _comboVar = new javax.swing.JComboBox();
        _buttonSistema = new javax.swing.JButton();
        _panelSystem = new javaapplication1.PanelSystem();
        _generaTabBut = new javax.swing.JButton();
        _errorMsg = new javax.swing.JLabel();
        _tableauPanel = new javaapplication1.TableauPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        _labelEq.setText("numero Equazioni:");

        _labelVar.setText("numero Variabili:");

        _comboEq.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));

        _comboVar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "6" }));

        _buttonSistema.setText("Genera Sistema");
        _buttonSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _buttonSistemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout _inputEqVarLayout = new javax.swing.GroupLayout(_inputEqVar);
        _inputEqVar.setLayout(_inputEqVarLayout);
        _inputEqVarLayout.setHorizontalGroup(
            _inputEqVarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_inputEqVarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(_inputEqVarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_labelEq)
                    .addComponent(_labelVar))
                .addGap(18, 18, 18)
                .addGroup(_inputEqVarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(_buttonSistema)
                    .addComponent(_comboVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_comboEq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        _inputEqVarLayout.setVerticalGroup(
            _inputEqVarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_inputEqVarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(_inputEqVarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_labelEq)
                    .addComponent(_comboEq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(_inputEqVarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_labelVar)
                    .addComponent(_comboVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(_buttonSistema)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        _generaTabBut.setText("Genera Tableau");
        _generaTabBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _generaTabButActionPerformed(evt);
            }
        });

        _errorMsg.setText("             ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_inputEqVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_panelSystem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(_tableauPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(_generaTabBut)
                        .addGap(71, 71, 71)
                        .addComponent(_errorMsg)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_inputEqVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_panelSystem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_generaTabBut)
                            .addComponent(_errorMsg)))
                    .addComponent(_tableauPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _buttonSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__buttonSistemaActionPerformed
        _panelSystem.setVisible(true);
        _generaTabBut.setVisible(true);
        _generaTabBut.setEnabled(true);
        _panelSystem.SetSystem(Integer.parseInt(_comboEq.getSelectedItem().toString()),Integer.parseInt(_comboVar.getSelectedItem().toString()));
    }//GEN-LAST:event__buttonSistemaActionPerformed

    private void _generaTabButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__generaTabButActionPerformed
        _generaTabBut.setEnabled(false);
        
        Frazione[][] generata = _panelSystem.GenerateMatrix(Integer.parseInt(_comboEq.getSelectedItem().toString()),Integer.parseInt(_comboVar.getSelectedItem().toString()));
        
               
        if(generata[0].length < generata.length)
        {   
            _errorMsg.setText("SISTEMA IMPOSSIBILE");
            _panelSystem.SetSystem(Integer.parseInt(_comboEq.getSelectedItem().toString()),Integer.parseInt(_comboVar.getSelectedItem().toString()));
            
        }
        else if(generata[0].length == generata.length)
        {   
            _errorMsg.setText("SISTEMA CON UN' UNICA SOLUZIONE");
            _panelSystem.SetSystem(Integer.parseInt(_comboEq.getSelectedItem().toString()),Integer.parseInt(_comboVar.getSelectedItem().toString()));
            
        }
        else 
            _tableauPanel.setTableau(new Tableau(generata),_panelSystem.isMin());//// METTERE TABELLA
            
    }//GEN-LAST:event__generaTabButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableauApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableauApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableauApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableauApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TableauApp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _buttonSistema;
    private javax.swing.JComboBox _comboEq;
    private javax.swing.JComboBox _comboVar;
    private javax.swing.JLabel _errorMsg;
    private javax.swing.JButton _generaTabBut;
    private javax.swing.JPanel _inputEqVar;
    private javax.swing.JLabel _labelEq;
    private javax.swing.JLabel _labelVar;
    private javaapplication1.PanelSystem _panelSystem;
    private javaapplication1.TableauPanel _tableauPanel;
    // End of variables declaration//GEN-END:variables
}
